# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
 adapter: mysql2
 encoding: utf8
 database: c9
 pool: 5

test:
 adapter: mysql2
 encoding: utf8
 database: c9
 pool: 5
  
production:
 adapter: mysql2
 encoding: utf8
 database: c9
 pool: 5